const items=[
    {
        id:1,
        imgscr:'images/campus/c1.webp',
        rating:{
            stars:4.2,
            noOfReviwes:10400,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Campus',
        itemName:'Men Running Shoes',
        currentPrice:1101,
        originalPrice:1899,
        discountPercentage:42,
    },
    {
        id:2,
        imgscr:'images/campus/c2.webp',
        rating:{
            stars:3.8,
            noOfReviwes:391,
        },
        returnPeriod:14,
        deliveryDate:'14 Oct 2023',
        companyName:'Campus',
        itemName:'Men Perforated Sneakers',
        currentPrice:699,
        originalPrice:1399,
        discountPercentage:50,
    },
    {
        id:3,
        imgscr:'images/campus/c3.webp',
        rating:{
            stars:3.8,
            noOfReviwes:23,
        },
        returnPeriod:14,
        deliveryDate:'11 Oct 2023',
        companyName:'Campus',
        itemName:'Men Lace Up Running Shoes',
        currentPrice:899,
        originalPrice:1799,
        discountPercentage:50,
    },
    {
        id:4,
        imgscr:'images/campus/c4.webp',
        rating:{
            stars:4.2,
            noOfReviwes:9100,
        },
        returnPeriod:14,
        deliveryDate:'17 Oct 2023',
        companyName:'Campus',
        itemName:'Men Running Shoes',
        currentPrice:1101,
        originalPrice:1899,
        discountPercentage:42,
    },
    {
        id:5,
        imgscr:'images/campus/cl.webp',
        rating:{
            stars:4.2,
            noOfReviwes:3400,
        },
        returnPeriod:14,
        deliveryDate:'10 Oct 2023',
        companyName:'Carlton London',
        itemName:'Men Lightweigth Loafers',
        currentPrice:1349,
        originalPrice:2999,
        discountPercentage:55,
    },
    {
        id:6,
        imgscr:'images/campus/d1.webp',
        rating:{
            stars:4.9,
            noOfReviwes:7,
        },
        returnPeriod:14,
        deliveryDate:'17 Oct 2023',
        companyName:'Duke',
        itemName:'Men Training & Gym Shoes',
        currentPrice:1558,
        originalPrice:3895,
        discountPercentage:60,
    },
    {
        id:7,
        imgscr:'images/campus/c5.webp',
        rating:{
            stars:4.2,
            noOfReviwes:3400,
        },
        returnPeriod:14,
        deliveryDate:'14 Oct 2023',
        companyName:'Campus',
        itemName:'Men Running Shoes',
        currentPrice:714,
        originalPrice:1299,
        discountPercentage:45,
    },
    {
        id:8,
        imgscr:'images/campus/c6.webp',
        rating:{
            stars:4.2,
            noOfReviwes:9000,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Campus',
        itemName:'Men Running Shoes',
        currentPrice:1101,
        originalPrice:1899,
        discountPercentage:42,
    },
    {
        id:9,
        imgscr:'images/campus/c7.webp',
        rating:{
            stars:4,
            noOfReviwes:1100,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Campus',
        itemName:'Men Running Shoes',
        currentPrice:985,
        originalPrice:1699,
        discountPercentage:42,
    },
    {
        id:10,
        imgscr:'images/campus/fm1.webp',
        rating:{
            stars:4,
            noOfReviwes:209,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Flying Machine',
        itemName:'Men Lamar Textured Sneakers',
        currentPrice:1499,
        originalPrice:2999,
        discountPercentage:50,
    },
    {
        id:11,
        imgscr:'images/campus/fm2.webp',
        rating:{
            stars:4.3,
            noOfReviwes:278,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Flying Machine',
        itemName:'Men Perforated Sneakers',
        currentPrice:1799,
        originalPrice:3599,
        discountPercentage:50,
    },
    {
        id:12,
        imgscr:'images/campus/fm3.webp',
        rating:{
            stars:4.3,
            noOfReviwes:287,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Flying Machine',
        itemName:'Men Colorblocked Sneakers',
        currentPrice:979,
        originalPrice:2799,
        discountPercentage:65,
    },
    {
        id:13,
        imgscr:'images/campus/p1.webp',
        rating:{
            stars:4,
            noOfReviwes:207,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Flying Machine',
        itemName:'Men Colorblocked Sneakers',
        currentPrice:9,
        originalPrice:200,
        discountPercentage:70,
    },
    {
        id:1,
        imgscr:'images/campus/c1.webp',
        rating:{
            stars:4.2,
            noOfReviwes:10400,
        },
        returnPeriod:14,
        deliveryDate:'13 Oct 2023',
        companyName:'Abhishek',
        itemName:'Men Running Shoes',
        currentPrice:1101,
        originalPrice:1899,
        discountPercentage:42,
    },
];